name: Update and Render Quarto

on:
  repository_dispatch:
    types: [update-from-repo]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout weijie-chen repository
      uses: actions/checkout@v3

    - name: Clone independent repositories
      run: |
        git clone https://github.com/weijie-chen/Basic-Statistics-With-Python /tmp/Basic-Statistics-With-Python
        git clone https://github.com/weijie-chen/Bayesian-Statistics-Econometrics /tmp/Bayesian-Statistics-Econometrics
        git clone https://github.com/weijie-chen/Econometrics-With-Python /tmp/Econometrics-With-Python
        git clone https://github.com/weijie-chen/Linear-Algebra-With-Python /tmp/Linear-Algebra-With-Python
        git clone https://github.com/weijie-chen/Time-Series-and-Financial-Engineering-With-Python /tmp/Time-Series-and-Financial-Engineering-With-Python

    - name: Clone virtualenv_management repository
      run: git clone https://github.com/weijie-chen/virtualenv_management /tmp/virtualenv_management

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Poetry
      run: curl -sSL https://install.python-poetry.org | python3 -

    - name: Install dependencies
      run: |
        cd /tmp/virtualenv_management
        poetry install

    - name: Install Quarto
      run: |
        wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.2.313/quarto-1.2.313-linux-amd64.deb
        sudo dpkg -i quarto-1.2.313-linux-amd64.deb
        echo 'PATH=/opt/quarto/bin:$PATH' >> $GITHUB_ENV

    - name: Verify Quarto installation
      run: |
        # Ensure necessary commands are available
        sudo apt-get update
        sudo apt-get install -y coreutils
        source $GITHUB_ENV
        quarto --version

    - name: Install Jupyter and dependencies
      run: |
        python3 -m pip install jupyter nbformat nbclient

    - name: Set up Poetry environment for Quarto
      run: |
        cd /tmp/virtualenv_management
        echo "$(poetry env info --path)/bin" >> $GITHUB_PATH
        source $(poetry env info --path)/bin/activate
        python3 -m ipykernel install --user --name=$(basename $(poetry env info --path))

    - name: Copy and convert .ipynb to .qmd
      run: |
        # Define the copy and convert functions
        copy_repo_contents() {
          local sourceDir="$1"
          local targetDir="$2"

          if [ -d "$targetDir" ]; then
              rm -rf "$targetDir"
          fi
          cp -r "$sourceDir" "$targetDir"
        }

        convert_ipynb_to_qmd() {
          local path="$1"
          find "$path" -name '*.ipynb' -exec quarto convert {} \;
          find "$path" -name '*.ipynb' -delete
        }

        new_quarto_yml() {
          local path="$1"
          local projectTitle="$2"

          chapters=$(find "$path" -name '*.qmd' | sort)

          # Initialize the YAML content
          yml_content="project:\n  type: book\n  title: \"$projectTitle\"\n\nbook:\n  chapters:\n"

          # Append each chapter to the YAML content
          while IFS= read -r chapter; do
              chapter_name=$(basename "$chapter" .qmd)
              relative_path=$(realpath --relative-to="$path" "$chapter")
              yml_content+="    - chapter: \"$chapter_name\"\n      file: \"$relative_path\"\n"
          done <<< "$chapters"

          # Write the YAML content to _quarto.yml
          echo -e "$yml_content" > "$path/_quarto.yml"
        }

        # Copy and convert for each repository
        declare -A repos=(
          ["Basic Statistics"]="/tmp/Basic-Statistics-With-Python:${GITHUB_WORKSPACE}/basic-statistics"
          ["Bayesian Statistics"]="/tmp/Bayesian-Statistics-Econometrics:${GITHUB_WORKSPACE}/bayesian-statistics"
          ["Econometrics"]="/tmp/Econometrics-With-Python:${GITHUB_WORKSPACE}/econometrics"
          ["Linear Algebra"]="/tmp/Linear-Algebra-With-Python:${GITHUB_WORKSPACE}/linear-algebra"
          ["Financial Engineering"]="/tmp/Time-Series-and-Financial-Engineering-With-Python:${GITHUB_WORKSPACE}/financial-engineering"
        )

        for title in "${!repos[@]}"; do
          IFS=':' read -r source target <<< "${repos[$title]}"
          echo "Processing repository: $source"
          
          # Copy contents
          copy_repo_contents "$source" "$target"
          
          # Convert .ipynb files to .qmd and remove .ipynb files
          convert_ipynb_to_qmd "$target"
          
          # Generate _quarto.yml
          new_quarto_yml "$target" "$title"
        done

    - name: Render Quarto project
      run: |
        cd /tmp/virtualenv_management
        source $(poetry env info --path)/bin/activate
        quarto render

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4.0.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
